export type Product = {
  slug: string;
  title: string;
  arabicTitle?: string;
  category: string;
  categorySlug: string;
  collection: string;
  collectionSlug: string;
  description: string;
  image: string;
  displayImage?: string;
  detailImage?: string;
  gallery?: string[];
  detailChips?: string[];
  imageQuality?: 'clean' | 'acceptable' | 'watermark' | 'weak';
  displayPriority?: number;
  cardVariant?: 'bag' | 'accessory' | 'canvas-custom';
  priceGuide: string;
};

export const collections = [
  { slug: 'himalayan-thread-bags', title: 'Himalayan Thread Bags', arabicTitle: 'شنط خيط الهيمالايا' },
  { slug: 'chain-thread-bags', title: 'Chain Thread Bags', arabicTitle: 'شنط خيوط السلسلة' },
  { slug: 'canvas-art', title: 'Canvas Art', arabicTitle: 'لوحات كانفس' },
  { slug: 'hair-accessories', title: 'Hair Accessories', arabicTitle: 'إكسسوارات شعر' }
];

export const products: Product[] = [
  { slug: 'black-gold-chain-thread-bag', title: 'Black Gold Chain Thread Bag', arabicTitle: 'شنطة خيوط السلسلة أسود وذهبي', category: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'شنط خيوط السلسلة', collectionSlug: 'chain-thread-bags', description: 'شنطة هاند ميد بخيوط السلسلة باللون الأسود مع تفاصيل ذهبية أنيقة، قطعة فاخرة تضيف لمسة قوية وناعمة لإطلالتك.', image: '/images/bahja/bags-chain-thread/chain-thread-bag-black-gold-chain-03.webp', displayImage: '/images/bahja/redesigned/black-gold-chain/black-gold-chain-thread-bag-card.png', detailImage: '/images/bahja/redesigned/black-gold-chain/black-gold-chain-thread-bag-card.png', gallery: ['/images/bahja/redesigned/black-gold-chain/black-gold-chain-thread-bag-card.png', '/images/bahja/bags-chain-thread/chain-thread-bag-black-gold-chain-03.webp'], detailChips: ['Handmade', 'Made to order', 'Custom colors', 'Chain options'], imageQuality: 'clean', displayPriority: 1, cardVariant: 'bag', priceGuide: 'صغير: 340 جنيه • متوسط: 450 جنيه • كبير: 590 جنيه' },
  { slug: 'light-grey-himalayan-thread-bag', title: 'Light Grey Himalayan Thread Bag', arabicTitle: 'شنطة خيط هيمالايا رمادي فاتح', category: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'شنط خيط الهيمالايا', collectionSlug: 'himalayan-thread-bags', description: 'شنطة هاند ميد بخيط هيمالايا رمادي فاتح، بتفاصيل أنيقة ولمسة دافئة مناسبة لإطلالاتك اليومية.', image: '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-light-grey-gold-chain-03.webp', displayImage: '/images/bahja/redesigned/light-grey-himalayan/light-grey-himalayan-thread-bag-card.png', detailImage: '/images/bahja/redesigned/light-grey-himalayan/light-grey-himalayan-thread-bag-card.png', gallery: ['/images/bahja/redesigned/light-grey-himalayan/light-grey-himalayan-thread-bag-card.png', '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-light-grey-gold-chain-03.webp'], detailChips: ['Handmade', 'Made to order', 'Custom colors', 'Chain options'], imageQuality: 'clean', displayPriority: 2, cardVariant: 'bag', priceGuide: 'صغير: 300 جنيه • متوسط: 400 جنيه • كبير: 470 جنيه' },
  { slug: 'navy-himalayan-thread-bag', title: 'Navy Himalayan Thread Bag', arabicTitle: 'شنطة خيط هيمالايا كحلي', category: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'شنط خيط الهيمالايا', collectionSlug: 'himalayan-thread-bags', description: 'شنطة هاند ميد بخيط هيمالايا كحلي، بتصميم أنثوي هادئ وتفاصيل يدوية متقنة تضيف لمسة فاخرة لإطلالتك.', image: '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-navy-lifestyle-02.webp', displayImage: '/images/bahja/redesigned/navy-himalayan/navy-himalayan-thread-bag-card.png', detailImage: '/images/bahja/redesigned/navy-himalayan/navy-himalayan-thread-bag-card.png', gallery: ['/images/bahja/redesigned/navy-himalayan/navy-himalayan-thread-bag-card.png', '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-navy-lifestyle-02.webp'], detailChips: ['Handmade', 'Made to order', 'Custom colors', 'Chain options'], imageQuality: 'clean', displayPriority: 3, cardVariant: 'bag', priceGuide: 'صغير: 300 جنيه • متوسط: 400 جنيه • كبير: 470 جنيه' },
  { slug: 'soft-sage-chain-thread-bag', title: 'Soft Sage Chain Thread Bag', arabicTitle: 'شنطة خيوط السلسلة ساج ناعم', category: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'شنط خيوط السلسلة', collectionSlug: 'chain-thread-bags', description: 'شنطة ساج ناعم بخيوط سلسلة تمنحك لمسة عصرية راقية.', image: '/images/bahja/bags-chain-thread/chain-thread-bag-soft-sage-lifestyle-01.webp', imageQuality: 'clean', displayPriority: 4, cardVariant: 'bag', priceGuide: 'صغير: 340 جنيه • متوسط: 450 جنيه • كبير: 590 جنيه' },
  { slug: 'silver-grey-chain-thread-bag', title: 'Silver Grey Chain Thread Bag', arabicTitle: 'شنطة خيوط سلسلة رمادي فضي', category: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'شنط خيوط السلسلة', collectionSlug: 'chain-thread-bags', description: 'درجات رمادي فضي مع تفاصيل خيوط أنيقة لإطلالة متوازنة ومميزة.', image: '/images/bahja/bags-chain-thread/chain-thread-bag-silver-grey-closeup-02.webp', imageQuality: 'acceptable', displayPriority: 5, cardVariant: 'bag', priceGuide: 'صغير: 340 جنيه • متوسط: 450 جنيه • كبير: 590 جنيه' },
  { slug: 'teal-himalayan-thread-bag', title: 'Teal Himalayan Thread Bag', arabicTitle: 'شنطة خيط هيمالايا تركواز', category: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'شنط خيط الهيمالايا', collectionSlug: 'himalayan-thread-bags', description: 'شنطة هاند ميد بخيط هيمالايا تركواز، بلون عميق وتفاصيل ذهبية ناعمة تضيف لمسة مميزة لإطلالتك.', image: '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-teal-gold-chain-01.webp', displayImage: '/images/bahja/redesigned/teal-himalayan/teal-himalayan-thread-bag-card.png', detailImage: '/images/bahja/redesigned/teal-himalayan/teal-himalayan-thread-bag-card.png', gallery: ['/images/bahja/redesigned/teal-himalayan/teal-himalayan-thread-bag-card.png', '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-teal-gold-chain-01.webp'], detailChips: ['Handmade', 'Made to order', 'Custom colors', 'Chain options'], imageQuality: 'clean', displayPriority: 90, cardVariant: 'bag', priceGuide: 'صغير: 300 جنيه • متوسط: 400 جنيه • كبير: 470 جنيه' },
  { slug: 'dusty-pink-satin-hair-accessories', title: 'Dusty Pink Satin Hair Accessories', arabicTitle: 'إكسسوارات شعر ساتان وردي هادئ', category: 'إكسسوارات شعر', categorySlug: 'hair-accessories', collection: 'إكسسوارات شعر', collectionSlug: 'hair-accessories', description: 'إكسسوارات ساتان وردي هادئ تضيف لمسة أنثوية رقيقة.', image: '/images/bahja/hair-accessories/satin-hair-accessories-dusty-pink-01.webp', imageQuality: 'clean', displayPriority: 120, cardVariant: 'accessory', priceGuide: 'متاح حسب الطلب' },
  { slug: 'ice-blue-satin-hair-accessories', title: 'Ice Blue Satin Hair Accessories', arabicTitle: 'إكسسوارات شعر ساتان أزرق ثلجي', category: 'إكسسوارات شعر', categorySlug: 'hair-accessories', collection: 'إكسسوارات شعر', collectionSlug: 'hair-accessories', description: 'إكسسوارات ساتان أزرق ثلجي بتفاصيل ناعمة وخفيفة.', image: '/images/bahja/hair-accessories/satin-hair-accessories-ice-blue-03.webp', imageQuality: 'acceptable', displayPriority: 121, cardVariant: 'accessory', priceGuide: 'متاح حسب الطلب' },
  { slug: 'royal-blue-satin-hair-accessories', title: 'Royal Blue Satin Hair Accessories', arabicTitle: 'إكسسوارات شعر ساتان أزرق ملكي', category: 'إكسسوارات شعر', categorySlug: 'hair-accessories', collection: 'إكسسوارات شعر', collectionSlug: 'hair-accessories', description: 'إكسسوارات ساتان أزرق ملكي بتوازن أنيق ولمسة أنثوية جذابة.', image: '/images/bahja/hair-accessories/satin-hair-accessories-royal-blue-02.webp', imageQuality: 'acceptable', displayPriority: 122, cardVariant: 'accessory', priceGuide: 'متاح حسب الطلب' },
  { slug: 'arabic-calligraphy-floral-canvas', title: 'Arabic Calligraphy Floral Canvas', arabicTitle: 'لوحة كانفس بالخط العربي والزهور', category: 'لوحات كانفس', categorySlug: 'canvas-art', collection: 'لوحات كانفس', collectionSlug: 'canvas-art', description: 'لوحة كانفس فنية تمزج بين الخط العربي والزهور بروح دافئة.', image: '/images/bahja/canvas-art/canvas-arabic-calligraphy-floral-01.webp', imageQuality: 'weak', displayPriority: 200, cardVariant: 'canvas-custom', priceGuide: 'متاح حسب الطلب' }
];
