export type ProductVisibility = 'public' | 'review';

export type Product = {
  slug: string;
  title: string;
  arabicTitle: string;
  category: string;
  categoryAr: string;
  categorySlug: string;
  collection: string;
  collectionAr: string;
  collectionSlug: string;
  description: string;
  descriptionAr: string;
  descriptionEn: string;
  image: string;
  displayImage?: string;
  detailImage?: string;
  gallery?: string[];
  detailChips?: string[];
  imageQuality?: 'clean' | 'acceptable' | 'watermark' | 'weak';
  displayPriority?: number;
  cardVariant?: 'bag' | 'accessory' | 'canvas-custom';
  priceGuide: string;
  status: ProductVisibility;
  tags?: string[];
  whatsappInquiryText?: string;
};

export const collections = [
  { slug: 'himalayan-thread-bags', title: 'Himalayan Thread Bags', arabicTitle: 'شنط خيط الهيمالايا' },
  { slug: 'chain-thread-bags', title: 'Chain Thread Bags', arabicTitle: 'شنط خيوط السلسلة' },
  { slug: 'canvas-art', title: 'Canvas Art', arabicTitle: 'لوحات كانفس' },
  { slug: 'hair-accessories', title: 'Hair Accessories', arabicTitle: 'إكسسوارات شعر' }
];

export const products: Product[] = [
  { slug: 'black-gold-chain-thread-bag', title: 'Black Gold Chain Thread Bag', arabicTitle: 'شنطة خيوط السلسلة أسود وذهبي', category: 'Handmade Bags', categoryAr: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'Chain Thread Bags', collectionAr: 'شنط خيوط السلسلة', collectionSlug: 'chain-thread-bags', description: 'شنطة هاند ميد بخيوط السلسلة باللون الأسود مع تفاصيل ذهبية أنيقة، قطعة قوية بلمسة ناعمة.', descriptionAr: 'شنطة هاند ميد بخيوط السلسلة باللون الأسود مع تفاصيل ذهبية أنيقة، قطعة قوية بلمسة ناعمة.', descriptionEn: 'Handmade chain-thread bag in black with elegant gold details.', image: '/images/bahja/bags-chain-thread/chain-thread-bag-black-gold-chain-03.webp', displayImage: '/images/bahja/redesigned/black-gold-chain/black-gold-chain-thread-bag-card.png', detailImage: '/images/bahja/redesigned/black-gold-chain/black-gold-chain-thread-bag-card.png', gallery: ['/images/bahja/redesigned/black-gold-chain/black-gold-chain-thread-bag-card.png', '/images/bahja/bags-chain-thread/chain-thread-bag-black-gold-chain-03.webp'], detailChips: ['Handmade', 'Made to order', 'Custom colors', 'Chain options'], imageQuality: 'clean', displayPriority: 1, cardVariant: 'bag', priceGuide: 'صغير: 340 جنيه • متوسط: 450 جنيه • كبير: 590 جنيه', status: 'public', tags: ['chain-thread', 'black', 'gold'], whatsappInquiryText: 'استفسار عن شنطة خيوط السلسلة أسود وذهبي' },
  { slug: 'light-grey-himalayan-thread-bag', title: 'Light Grey Himalayan Thread Bag', arabicTitle: 'شنطة خيط هيمالايا رمادي فاتح', category: 'Handmade Bags', categoryAr: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'Himalayan Thread Bags', collectionAr: 'شنط خيط الهيمالايا', collectionSlug: 'himalayan-thread-bags', description: 'شنطة هاند ميد بخيط هيمالايا رمادي فاتح، بتفاصيل أنيقة ولمسة دافئة مناسبة لإطلالاتك اليومية.', descriptionAr: 'شنطة هاند ميد بخيط هيمالايا رمادي فاتح، بتفاصيل أنيقة ولمسة دافئة مناسبة لإطلالاتك اليومية.', descriptionEn: 'Handmade Himalayan-thread bag in light grey for calm daily looks.', image: '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-light-grey-gold-chain-03.webp', displayImage: '/images/bahja/redesigned/light-grey-himalayan/light-grey-himalayan-thread-bag-card.png', detailImage: '/images/bahja/redesigned/light-grey-himalayan/light-grey-himalayan-thread-bag-card.png', gallery: ['/images/bahja/redesigned/light-grey-himalayan/light-grey-himalayan-thread-bag-card.png', '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-light-grey-gold-chain-03.webp'], detailChips: ['Handmade', 'Made to order', 'Custom colors', 'Chain options'], imageQuality: 'clean', displayPriority: 2, cardVariant: 'bag', priceGuide: 'صغير: 300 جنيه • متوسط: 400 جنيه • كبير: 470 جنيه', status: 'public' },
  { slug: 'navy-himalayan-thread-bag', title: 'Navy Himalayan Thread Bag', arabicTitle: 'شنطة خيط هيمالايا كحلي', category: 'Handmade Bags', categoryAr: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'Himalayan Thread Bags', collectionAr: 'شنط خيط الهيمالايا', collectionSlug: 'himalayan-thread-bags', description: 'شنطة هاند ميد بخيط هيمالايا كحلي، بتصميم أنثوي هادئ وتفاصيل يدوية متقنة.', descriptionAr: 'شنطة هاند ميد بخيط هيمالايا كحلي، بتصميم أنثوي هادئ وتفاصيل يدوية متقنة.', descriptionEn: 'Handmade Himalayan-thread bag in navy with a soft elegant finish.', image: '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-navy-lifestyle-02.webp', displayImage: '/images/bahja/redesigned/navy-himalayan/navy-himalayan-thread-bag-card.png', detailImage: '/images/bahja/redesigned/navy-himalayan/navy-himalayan-thread-bag-card.png', gallery: ['/images/bahja/redesigned/navy-himalayan/navy-himalayan-thread-bag-card.png', '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-navy-lifestyle-02.webp'], imageQuality: 'clean', displayPriority: 3, cardVariant: 'bag', priceGuide: 'صغير: 300 جنيه • متوسط: 400 جنيه • كبير: 470 جنيه', status: 'public' },
  { slug: 'soft-sage-chain-thread-bag', title: 'Soft Sage Chain Thread Bag', arabicTitle: 'شنطة خيوط السلسلة ساج هادئ', category: 'Handmade Bags', categoryAr: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'Chain Thread Bags', collectionAr: 'شنط خيوط السلسلة', collectionSlug: 'chain-thread-bags', description: 'شنطة هاند ميد بخيوط السلسلة بدرجة ساج هادئة، وتجهيز حسب الطلب حسب اللون المتاح.', descriptionAr: 'شنطة هاند ميد بخيوط السلسلة بدرجة ساج هادئة، وتجهيز حسب الطلب حسب اللون المتاح.', descriptionEn: 'Handmade chain-thread bag in soft sage, made to order.', image: '/images/bahja/bags-chain-thread/chain-thread-bag-soft-sage-lifestyle-01.webp', displayImage: '/images/bahja/redesigned/soft-sage-chain/soft-sage-chain-thread-bag-card.png', detailImage: '/images/bahja/redesigned/soft-sage-chain/soft-sage-chain-thread-bag-card.png', gallery: ['/images/bahja/redesigned/soft-sage-chain/soft-sage-chain-thread-bag-card.png', '/images/bahja/bags-chain-thread/chain-thread-bag-soft-sage-lifestyle-01.webp'], imageQuality: 'clean', displayPriority: 4, cardVariant: 'bag', priceGuide: 'صغير: 340 جنيه • متوسط: 450 جنيه • كبير: 590 جنيه', status: 'public' },
  { slug: 'silver-grey-chain-thread-bag', title: 'Silver Grey Chain Thread Bag', arabicTitle: 'شنطة خيوط السلسلة رمادي فضي', category: 'Handmade Bags', categoryAr: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'Chain Thread Bags', collectionAr: 'شنط خيوط السلسلة', collectionSlug: 'chain-thread-bags', description: 'شنطة هاند ميد بخيوط السلسلة بلون رمادي فضي، بتفاصيل هادئة تناسب اليومي والمناسبات.', descriptionAr: 'شنطة هاند ميد بخيوط السلسلة بلون رمادي فضي، بتفاصيل هادئة تناسب اليومي والمناسبات.', descriptionEn: 'Handmade chain-thread bag in silver grey with calm styling.', image: '/images/bahja/bags-chain-thread/chain-thread-bag-silver-grey-closeup-02.webp', displayImage: '/images/bahja/redesigned/silver-grey-chain/silver-grey-chain-thread-bag-card.png', detailImage: '/images/bahja/redesigned/silver-grey-chain/silver-grey-chain-thread-bag-card.png', gallery: ['/images/bahja/redesigned/silver-grey-chain/silver-grey-chain-thread-bag-card.png', '/images/bahja/bags-chain-thread/chain-thread-bag-silver-grey-closeup-02.webp'], imageQuality: 'clean', displayPriority: 5, cardVariant: 'bag', priceGuide: 'صغير: 340 جنيه • متوسط: 450 جنيه • كبير: 590 جنيه', status: 'public' },
  { slug: 'teal-himalayan-thread-bag', title: 'Teal Himalayan Thread Bag', arabicTitle: 'شنطة خيط هيمالايا تركواز', category: 'Handmade Bags', categoryAr: 'شنط هاند ميد', categorySlug: 'handmade-bags', collection: 'Himalayan Thread Bags', collectionAr: 'شنط خيط الهيمالايا', collectionSlug: 'himalayan-thread-bags', description: 'شنطة هاند ميد بخيط هيمالايا تركواز، بلون عميق وتفاصيل ناعمة.', descriptionAr: 'شنطة هاند ميد بخيط هيمالايا تركواز، بلون عميق وتفاصيل ناعمة.', descriptionEn: 'Handmade Himalayan-thread bag in teal.', image: '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-teal-gold-chain-01.webp', displayImage: '/images/bahja/redesigned/teal-himalayan/teal-himalayan-thread-bag-card.png', detailImage: '/images/bahja/redesigned/teal-himalayan/teal-himalayan-thread-bag-card.png', gallery: ['/images/bahja/redesigned/teal-himalayan/teal-himalayan-thread-bag-card.png', '/images/bahja/bags-himalayan-thread/himalayan-thread-bag-teal-gold-chain-01.webp'], imageQuality: 'clean', displayPriority: 90, cardVariant: 'bag', priceGuide: 'صغير: 300 جنيه • متوسط: 400 جنيه • كبير: 470 جنيه', status: 'public' },
  { slug: 'dusty-pink-satin-hair-accessories', title: 'Dusty Pink Satin Hair Accessories', arabicTitle: 'إكسسوارات شعر ساتان وردي هادئ', category: 'Hair Accessories', categoryAr: 'إكسسوارات شعر', categorySlug: 'hair-accessories', collection: 'Hair Accessories', collectionAr: 'إكسسوارات شعر', collectionSlug: 'hair-accessories', description: 'إكسسوارات ساتان وردي هادئ تضيف لمسة أنثوية رقيقة.', descriptionAr: 'إكسسوارات ساتان وردي هادئ تضيف لمسة أنثوية رقيقة.', descriptionEn: 'Soft satin accessories in dusty pink.', image: '/images/bahja/hair-accessories/satin-hair-accessories-dusty-pink-01.webp', imageQuality: 'clean', displayPriority: 120, cardVariant: 'accessory', priceGuide: 'متاح حسب الطلب', status: 'public' },
  { slug: 'ice-blue-satin-hair-accessories', title: 'Ice Blue Satin Hair Accessories', arabicTitle: 'إكسسوارات شعر ساتان أزرق ثلجي', category: 'Hair Accessories', categoryAr: 'إكسسوارات شعر', categorySlug: 'hair-accessories', collection: 'Hair Accessories', collectionAr: 'إكسسوارات شعر', collectionSlug: 'hair-accessories', description: 'إكسسوارات ساتان أزرق ثلجي بتفاصيل ناعمة وخفيفة.', descriptionAr: 'إكسسوارات ساتان أزرق ثلجي بتفاصيل ناعمة وخفيفة.', descriptionEn: 'Satin hair accessories in ice blue.', image: '/images/bahja/hair-accessories/satin-hair-accessories-ice-blue-03.webp', imageQuality: 'acceptable', displayPriority: 121, cardVariant: 'accessory', priceGuide: 'متاح حسب الطلب', status: 'public' },
  { slug: 'royal-blue-satin-hair-accessories', title: 'Royal Blue Satin Hair Accessories', arabicTitle: 'إكسسوارات شعر ساتان أزرق ملكي', category: 'Hair Accessories', categoryAr: 'إكسسوارات شعر', categorySlug: 'hair-accessories', collection: 'Hair Accessories', collectionAr: 'إكسسوارات شعر', collectionSlug: 'hair-accessories', description: 'إكسسوارات ساتان أزرق ملكي بتوازن أنيق ولمسة أنثوية.', descriptionAr: 'إكسسوارات ساتان أزرق ملكي بتوازن أنيق ولمسة أنثوية.', descriptionEn: 'Satin hair accessories in royal blue.', image: '/images/bahja/hair-accessories/satin-hair-accessories-royal-blue-02.webp', imageQuality: 'acceptable', displayPriority: 122, cardVariant: 'accessory', priceGuide: 'متاح حسب الطلب', status: 'public' },
  { slug: 'arabic-calligraphy-floral-canvas', title: 'Arabic Calligraphy Floral Canvas', arabicTitle: 'لوحة كانفس بالخط العربي والزهور', category: 'Canvas Art', categoryAr: 'لوحات كانفس', categorySlug: 'canvas-art', collection: 'Canvas Art', collectionAr: 'لوحات كانفس', collectionSlug: 'canvas-art', description: 'لوحة كانفس فنية تمزج بين الخط العربي والزهور بروح دافئة.', descriptionAr: 'لوحة كانفس فنية تمزج بين الخط العربي والزهور بروح دافئة.', descriptionEn: 'Custom floral canvas inspired by Arabic calligraphy.', image: '/images/bahja/canvas-art/canvas-arabic-calligraphy-floral-01.webp', imageQuality: 'weak', displayPriority: 200, cardVariant: 'canvas-custom', priceGuide: 'متاح حسب الطلب', status: 'review' }
];

export const publicProducts = products.filter((product) => product.status === 'public');
